all:
  hosts:
    psql-op-1-ubuntu-1:
      ansible_host: 89.169.135.117
      ansible_user: user
      ansible_ssh_pass: znykkkd
    psql-op-1-ubuntu-2:
      ansible_host: 51.250.12.1
      ansible_user: user
      ansible_ssh_pass: znykkkd
  vars:
    ansible_python_interpreter: /usr/bin/python3
